//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tMember
    {
        public int fId { get; set; }

        [DisplayName("帳號")]
        [Required(ErrorMessage = "帳號不可空白")]
        public string fUserId { get; set; }

        [DisplayName("密碼")]
        [Required(ErrorMessage = "密碼不可空白")]
        public string fPwd { get; set; }

        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名不可空白")]
        public string fName { get; set; }

        [DisplayName("信箱")]
        [EmailAddress(ErrorMessage = "E-Mail格式有誤")]
        [Required]
        public string fEmail { get; set; }

        [DisplayName("生日")]
        [DataType(DataType.Date, ErrorMessage = "雇用日期必須為日期格式")]
        [Required]
        public Nullable<System.DateTime> fBirth { get; set; }

        [DisplayName("是否是管理員")]
        public bool fIsAdmin { get; internal set; }
    }
}
